In [1]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([[1, 2], [3, 4]])
a3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [4]:
a1

array([1, 2, 3, 4])

In [5]:
a2

array([[1, 2],
       [3, 4]])

In [6]:
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
a = np.array([127, 128, 129], dtype=np.int8)

In [8]:
a

array([ 127, -128, -127], dtype=int8)